# Site settings
author: charming-archiver-3281
title: 
header-img: img/home-bg.png
email: tuonggvy.vo@gmail.com
copyright_name: charming-archiver-3281
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  votuongvy

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
